### ISSUE TITLE
Primer Trimming Option

### ISSUE THREAD

**Issue by RanWei1987** [niemasd/ViralConsensus#13]
Hello, when assigning an primer bed file using option -p/--primer_bed, a lot of Ns are seen in the final consensus genome, comparing to the counterpart without  -p/--primer_bed being defined. 

I have two observations: 
(1) On my side, some rows in the primer bed file have column 2 > column 3 to describe a primer mapped to the reverse strand. Should the bed file always define column 2 as smaller than column 3? 
(2) I notice in count.cpp, the logic to determine if a position of bam read should be taken into base calling is ` if(curr_base_qual >= min_qual && (!primer_trim || (!is_reverse && pos >= min_max_primer_inds[src->core.pos].second) || (is_reverse && pos < min_max_primer_inds[src->core.pos].first)))` I am wondering, if the primer region is [200, 300] and a bam read spanning [150, 450], will the region of [150, 199] be excluded from base calling (i.e. count the corresponding base to counts.pos_counts?

Thank you.

**Comment by niemasd** [comment]
Thanks for reaching out! 

> (1) On my side, some rows in the primer bed file have column 2 > column 3 to describe a primer mapped to the reverse strand. Should the bed file always define column 2 as smaller than column 3?

Ah, I think [my code](https://github.com/niemasd/ViralConsensus/blob/60f6e2c86dcb86e641b352b4a0831bf43d645cb1/primer.cpp#L3-L22) is assuming that column 2 will always be numerically smaller than column 3 in the BED file, but I imagine column 2 being larger implies a primer on the reverse strand, is that correct? I believe the later parts of my code break if column 2 is smaller than column 3, but I can push an update to handle this situation. Maybe I can just check which column is smaller and always store them as `(smaller, larger)` tuples, even if column 2 is the larger and column 3 is the smaller?

> (2) I notice in count.cpp, the logic to determine if a position of bam read should be taken into base calling is  `if(curr_base_qual >= min_qual && (!primer_trim || (!is_reverse && pos >= min_max_primer_inds[src->core.pos].second) || (is_reverse && pos < min_max_primer_inds[src->core.pos].first)))`

In order to count the base:

* The base quality must be >= the minimum threshold (`curr_base_qual >= min_qual`), AND
* It needs to be valid with respect to potential primer trimming:
  * Either we're not doing primer trimming at all (`!primer_trim`), OR
  * We're looking at the forward strand (`!is_reverse`) AND this base is at a larger position than the "end" of the primer that spans the map position (`pos >= min_max_primer_inds[src->core.pos].second` where "end" is the third column in the BED which I assume to be the larger column right now but can fix), OR
  * We're looking at the reverse strand (`is_reverse`) AND this base is at a smaller position than the "start" of the primer that spans the map position (`pos < min_max_primer_inds[src->core.pos].first` where "start" is the second column in the BED which I assume to be the smaller column right now but can fix)

But now that I think about it more, my idea for a potential simple fix above may not be correct: I wonder if I need to separate out "forward primers" (column 2 smaller than column 3) vs "reverse primers" (column 2 larger than column 3) and only check reverse reads (`is_reverse`) vs. "reverse primers". Does that sound about right? I Believe the primers I was using when testing were all "column 2 smaller than column 3", so I didn't realize my assumptions about this would be broken, but this should be handled carefully

Do you have an example dataset (reads BAM + reference genome FASTA + primer BED) as well as its expected output (consensus FASTA) that I could use to test my solution idea?

> I am wondering, if the primer region is [200, 300] and a bam read spanning [150, 450], will the region of [150, 199] be excluded from base calling (i.e. count the corresponding base to counts.pos_counts?

Let's just assume "forward strand" for this example to keep things simple. For a primer where column 2 is 200 and column 3 is 300, if you have a BAM spanning [150, 450], it will not be trimmed at all by this specific primer because the start position of the BAM mapping (150) is outside of the range of this specific primer ([200, 300]). This mapping would only have bases excluded from base calling if there's another primer where column 2 is less than or equal to 150 and column 3 is greater than 150 (i.e., a primer that spans the start position of this mapping)

**Comment by niemasd** [comment]
Labeling this as a bug, as I believe the current code is not at all handling BED files that may contain primers in which the column 2 value is larger than the column 3 value, which needs to be fixed regardless of the outcome of this specific issue. So thank you for catching that 😄

**Comment by RanWei1987** [comment]
Thank you for the quick response! Yes I think the fix you suggested should work.

I am attaching the example dataset here:

wnv_reference.fasta -  reference genome of west nile virus;
13_15.bam - the bam file after sequencing alignment
WNV.scheme.bed - the primer bed file
13_15.fasta - the consensus genome without defining primer bed file
13_15_n.fasta - the consensus genome with primer bed file defined (a lot more N)
[WNV Example.zip](https://github.com/user-attachments/files/17938330/WNV.Example.zip)

Please let me know if you need other stuff.

**Comment by niemasd** [comment]
Excellent; thank you for sharing! I will try to explore this as soon as possible. I'll follow up and tag you once I get a chance 😄

**Comment by RanWei1987** [comment]
Great, thank you!

**Comment by niemasd** [comment]
@RanWei1987 Okay, I just released a new version that has a fix for (hopefully) correctly supporting reverse primers in a BED file! Can you try it out?

https://github.com/niemasd/ViralConsensus/releases/tag/0.0.6

**Comment by RanWei1987** [comment]
Thank you! I am attaching the consensus genome file from the new version here (13_15_viralConsensus006.fasta). The consensus remains and the data quality improves with even fewer Ns.  Great work!
[WNV Example.zip](https://github.com/user-attachments/files/17983539/WNV.Example.zip)

**Comment by niemasd** [comment]
Awesome, glad to hear that the problem seems to be fixed 😄 I'll go ahead and close this GitHub Issue, but please feel free to reach out into any other issues! And thanks so much again for catching this!
